server:
  port: 8080

spring:
  session:
    jdbc:
      initialize-schema: always
  datasource:
    username: root
    password: 123456

    url: jdbc:mysql://mysql_db:3306/code_manage_system?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    initialize: true
  docker:
    compose:
      enabled: false
#  sql:
#    init:
#      schema-locations: classpath:/org/springframework/session/jdbc/schema-@@platform@@.sql
#      file: ./docker/compose.yaml

python-service:
  url: http://localhost
  port: 8088

db-port: 3306

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
  config: classpath:logback.xml