server:
  port: 8080

spring:
  session:
    jdbc:
      initialize-schema: always
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:13306/code_manage_system
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialize: true
  docker:
    compose:
      enabled: false
#  sql:
#    init:
#      schema-locations: classpath:/org/springframework/session/jdbc/schema-@@platform@@.sql
#      file: ./docker/compose.yaml

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
  config: classpath:logback.xml